include ../../Makefile.build

LDFLAGS += -lrt
SOURCES	+= main.cpp
#CXXFLAGS += -DEIGEN_NO_DEBUG
TARGET 	= test-calib-ukfellipsoid
#RELPATH	= ../../

LIBS=$(OPENAHRS_LIB)

include ../../Makefile.rules
