include ../../../Makefile.build

SOURCES	+= ../input/ad12.cpp ../input/lis3lv02.cpp ../input/ads1256.cpp main.cpp
TARGET 	= sensortest
#RELPATH	= ../../

LIBS=$(OPENAHRS_LIB)

include ../../../Makefile.rules
