include ../../Makefile.build

SOURCES	+= input/ads1256.cpp input/ad12.cpp input/lis3lv02.cpp input/mmap.cpp input/cflip.cpp avr32hw.cpp main.cpp
TARGET 	= ahrs
#RELPATH	= ../../

LIBS=$(OPENAHRS_LIB)

include ../../Makefile.rules
