include ../../Makefile.build

SOURCES	+= input/ad12.cpp input/lis3lv02.cpp input/mmap.cpp input/cflip.cpp main.cpp
TARGET 	= ahrs
#RELPATH	= ../../

LIBS=$(OPENAHRS_LIB)

include ../../Makefile.rules
